tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Packages
brew "difftastic"
brew "eza"
brew "git"
brew "helix"
brew "imagemagick"
brew "jd"
brew "jq"
brew "media-info"
brew "pwgen"
brew "ripgrep"
brew "sk"
brew "starship"
brew "zoxide"

# Casks
cask_args appdir: "/Applications"
cask "amethyst"
cask "firefox"
cask "homebrew/cask-fonts/font-iosevka"
cask "imageoptim"
cask "keepassxc"
cask "vscodium"
