palette = "catppuccin_frappe"
format = """
${custom.symbol}[](fg:rosewater)\
$username$hostname\
$directory\
$git_branch$git_status\
$time\
$fill\
${custom.right_side}\
$cmd_duration
$character
"""

[custom.symbol]
description = "The leading symbol of the prompt"
when = true
style = "fg:crust bg:rosewater"
format = "[  ]($style)"

[username]
show_always = true
style_user = "fg:pink"
format = "[$user@]($style)"

[hostname]
disabled = false
ssh_only = false
style = "fg:pink"
format = "[$hostname ]($style)"

[directory]
style = "fg:yellow"
format = "[$path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:green"
format = "[$symbol $branch]($style)"

[git_status]
style = "fg:green"
format = "[$all_status$ahead_behind ]($style)"

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format
style = "fg:lavender"
format = "[$time]($style)"

[fill]
disabled = false
symbol = " "

[custom.right_side]
description = "The fade out effect on the right side"
when = true
format = """
[](fg:surface0)\
[  ](fg:surface1 bg:surface0)\
[  ](fg:surface2 bg:surface1)\
[  ](fg:overlay0 bg:surface2)\
[  ](fg:overlay1 bg:overlay0)\
[  ](fg:overlay2 bg:overlay1)\
[  ](bg:overlay2)"""

[cmd_duration]
disabled = false
min_time = 1_000
format = "[$duration]($style)"
style = "fg:crust bg:overlay2"

[character]
success_symbol = "[›](fg:text)"
error_symbol = "[⨯](fg:red)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
