palette = "catppuccin_frappe"
format = """
$username$hostname\
$directory\
$git_branch$git_status\
$time\
$fill\
${custom.right_side}\
$cmd_duration
$character
"""

[username]
show_always = true
style_user = "fg:darker_bg bg:primary"
format = "[ $user@]($style)"

[hostname]
disabled = false
ssh_only = false
style = "fg:darker_bg bg:primary"
format = "[$hostname ]($style)[](fg:primary bg:darker_bg)"

[directory]
style = "fg:secondary bg:darker_bg"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style = "fg:darker_bg bg:tertiary"
format = "[ $symbol$branch]($style)"

[git_status]
style = "fg:darker_bg bg:tertiary"
format = "[$all_status$ahead_behind ]($style)[](fg:tertiary bg:darker_bg)"

[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format
style = "fg:quaternary bg:darker_bg"
format = "[ $time ]($style)[](fg:darker_bg)"

[fill]
disabled = false
symbol = " "

[custom.right_side]
description = "The fade out effect on the right side"
when = true
format = """
[](fg:surface0)\
[  ](fg:surface1 bg:surface0)\
[  ](fg:surface2 bg:surface1)\
[  ](fg:overlay0 bg:surface2)\
[  ](fg:overlay1 bg:overlay0)\
[  ](fg:overlay2 bg:overlay1)\
[  ](bg:overlay2)"""

[cmd_duration]
disabled = false
min_time = 1_000
format = "[$duration]($style)"
style = "fg:darker_bg bg:overlay2"

[character]
success_symbol = "[›](fg:text)"
error_symbol = "[⨯](fg:red)"

[palettes.catppuccin_frappe]
primary = "#f4b8e4" # pink
secondary = "#e5c890" # yellow
tertiary = "#a6d189" # green
quaternary = "#85c1dc" # sapphire
red = "#e78284" # red
text = "#c6d0f5" # text
overlay2 = "#949cbb" # overlay2
overlay1 = "#838ba7" # overlay1
overlay0 = "#737994" # overlay0
surface2 = "#626880" # surface2
surface1 = "#51576d" # surface1
surface0 = "#414559" # surface0
main_bg = "#303446" # base
darker_bg = "#232634" # crust
