set autoindent
set incsearch
set number
set ruler

" softtags, 2 spaces.
set tabstop=2
set shiftwidth=2
set expandtab

" enable syntax highlighting
syn on

" install plugins, needs vim-plug, see:
" https://github.com/junegunn/vim-plug
call plug#begin()
Plug 'catppuccin/nvim', { 'as': 'catppuccin' }
call plug#end()

" set catppuccin as theme
colorscheme catppuccin-frappe
