# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  docker
  fnm
  yarn
)

source $ZSH/oh-my-zsh.sh

# Includes
source $HOME/dotfiles/zsh/functions # load functions first
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/env

if type starship &> /dev/null; then
  eval "$(starship init zsh)"
fi
