# Includes
source $HOME/dotfiles/zsh/functions # load functions first
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/config
source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/env
source $HOME/dotfiles/zsh/additional-sources/*

# Initialize starship prompt
if type starship &> /dev/null; then
  eval "$(starship init zsh)"
fi

# Initialize zoxide as fuzzy directory finder
if type zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi
